config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :users
  resources :posts

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower, classname: "User"
  belongs_to :followed_by, classname: "User"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # has_many :follower_relationships, classname: "Relationship", foreign_key: "followed_id"
  # has_many :followed_relationships, classname: "Relationship", foreign_key: "follower_id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(:created_at).reverse
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.haml
%nav
  %a.main{:href => "#{root_url}"}
    Em☀️jer
  / responsive
  %input#bmenu.burgercheck{:type => "checkbox"}/
  %label.burgermenu{:for => "bmenu"}
  / /responsive
  .menu
    %a.icon-menu{:href => "#nav"} Nav
    = link_to_modal (fa_icon "pencil-square-o"), new_post_path, class: "button primary"
    / %a.button.primary{:href => "/posts/new"}
    /   = fa_icon "pencil-square-o"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Emojer
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render '/layouts/navbar'
    = yield

app/views/posts/_form.html.haml
.post-input
  = form_for @post do |f|
    - if @post.errors.any?
      #error_explanation
        %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
        %ul
          - @post.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.text_area :content, size: '30x5', class: 'emojis-wysiwyg'
      %a.emoji-button{:href => "javascript:void(0)", :title => "Emojis"} Emojis
    .actions.right
      = f.submit 'Post', class: 'primary'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.center
  - @posts.each do |post|
    - if post.content.present?
      .center.post
        .row
          .name-and-time
            = raw render_emoji (post.user.name), options = {:class=>'user-name'} if post.user.present?
            &middot;
            .post-time
              = time_ago_in_words(post.updated_at)
        .row
          .post-content
            = raw render_emoji post.content

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @post.content

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Password
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.password
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Password:
  = @user.password

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path